[review]
prompt = """
以下のPRの変更内容について、コードレビューを日本語でお願いします。
良い点、改善点、潜在的な問題があれば具体的に述べてください。
"""

[describe]
prompt = """
このPRの変更内容を日本語で要約してください。
目的・主な修正点・影響範囲を簡潔に書いてください。
"""

[improve]
prompt = """
このPRのコードをより良くするための改善提案を日本語で出してください。
リファクタリング、セキュリティ、保守性、パフォーマンスの観点で提案してください。
"""

