language = "ja"

[review]
prompt = "このPRのコードを **日本語で丁寧に** レビューしてください。"

[describe]
prompt = "このPRの変更内容を **日本語で簡潔に** 要約してください。"

[improve]
prompt = "このPRのコードを **改善するための提案** を日本語で出してください。"

[approve]
prompt = "このPRを **承認すべきか** を日本語で判断し、理由も書いてください。"

[help]
prompt = "このPRエージェントの使い方を **日本語で** 説明してください。"

