version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  back_end:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create && bin/rails db:migrate && bin/rails s -b 0.0.0.0 -p 3000"
    volumes:
      - ./back_end/tmp:/back_end/tmp
      - ./back_end:/back_end
    ports:
      - "3000:3000"
    depends_on:
      - db

  front_end:
      build:
        context: ./front_end
        dockerfile: Dockerfile
      volumes:
        - ./front_end:/app
      ports:
        - "8080:8080"

volumes:
  tmp:
