name: Trigger AI Review

on:
  issue_comment:
    types: [created]

jobs:
  check-team-member:
    if: github.event.comment.body == 'AIレビュー'
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check.outputs.allowed }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check if commenter is in team
        id: check
        run: |
          COMMENTER=${{ github.event.comment.user.login }}
          TEAM_MEMBERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/orgs/terumitt-dev/teams/ai-reviewers/members | jq -r '.[].login')

          if echo "$TEAM_MEMBERS" | grep -q "^$COMMENTER$"; then
            echo "allowed=true" >> "$GITHUB_OUTPUT"
          else
            echo "allowed=false" >> "$GITHUB_OUTPUT"
          fi

  ai-review:
    needs: check-team-member
    if: needs.check-team-member.outputs.allowed == 'true'
    uses: your-org/github_actions_ci-cd/.github/workflows/reusable-ci.yml@main
    with:
      pr_number: ${{ github.event.issue.number }}
    secrets:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

permissions:
  contents: read
  workflows: read
